=== nicktayl0r/agb/local_api/dependencies/grapes/project_editor/src/schema/rubricSchema.json
{
	"title": "Case Rubrics",
	"type": "object",
	"format": "grid",
	"$schema": "http://json-schema.org/draft-04/schema#",
	"required": ["devEnv", "stageEnv", "productionEnv", "rubrics"],
	"properties": {
		"rubrics": {
			"title": "Rubrics",
			"type": "array",
			"format": "tabs",
			"items": {
				"type": "object",
				"headerTemplate": "{{ self.key }}",
				"properties": {
					"trackL": {
						"type": "boolean",
						"format": "checkbox",
						"title": "Case Track L",
						"description": "Is this rubric used in the HS version of the case?"
					},
					"trackH": {
						"type": "boolean",
						"format": "checkbox",
						"title": "Handbook Track H",
						"description": "Is this rubric used in the H version of the handbook?"
					},
					"trackAP": {
						"type": "boolean",
						"format": "checkbox",
						"title": "Case Track AP",
						"description": "Is this rubric used in the AP version of the case?"
					},
					"trackA": {
						"type": "boolean",
						"format": "checkbox",
						"title": "Handbook Track AP",
						"description": "Is this rubric used in the AP version of the handbook?"
					},
					"trackE": {
						"type": "boolean",
						"format": "checkbox",
						"title": "Case Track ES",
						"description": "Is this rubric used in the ES version of the case?"
					},
					"trackEX": {
						"type": "boolean",
						"format": "checkbox",
						"title": "Handbook Track ES",
						"description": "Is this rubric used in the ES version of the handbook?"
					},
					"trackM": {
						"type": "boolean",
						"format": "checkbox",
						"title": "Case Track MS",
						"description": "Is this rubric used in the MS version of the case?"
					},
					"trackMX": {
						"type": "boolean",
						"format": "checkbox",
						"title": "Handbook Track MS",
						"description": "Is this rubric used in the MS version of the handbook?"
					},
					"key": {
						"type": "string",
						"title": "RubricID"
					},
					"brief": {
						"type": "string",
						"format": "textarea",
						"title": "Brief",
						"description": "A short summary of the question. Use the question text if the question text is short. (⁺ ,⁻ ,² ,₂ , ₃)"
					},
					"question": {
						"type": "string",
						"format": "textarea",
						"title": "Question",
						"description": "The full text of the question. (⁺ ,⁻ ,² ,₂ , ₃)"
					},
					"resource_activity_rubric_skills": {
						"title": "Skills",
						"type": "array",
						"format": "table",
						"items": {
							"type": "string",
							"enum": [
								"Core Concepts",
								"Data Analysis",
								"Data Interpretation",
								"Hypothesis & Reasoning",
								"Predictions",
								"Communicating Findings"
							]
						}
					},
					"resource_activity_rubric_type": {
						"type": "string",
						"enum": [
							"Short Answer",
							"Short Answer",
							"Long Answer",
							"Multiple Choice",
							"Repeat Attempts",
							"Repeat Attempts",
							"Integer",
							"Fraction",
							"Image"
						],
						"options": {
							"enum_titles": [
								"Short Answer",
								"Short Answer [revisable]",
								"Long Answer",
								"Multiple Choice",
								"Repeat Attempts",
								"Repeat Attempts [drag and drop]",
								"Integer",
								"Fraction",
								"Image"
							]
						}
					},
					"autograde": {
						"type": "boolean",
						"format": "checkbox",
						"title": "Autograded",
						"description": "False for short and long answer."
					},
					"resource_activity_rubric_answers": {
						"title": "Answers",
						"type": "array",
						"format": "table",
						"items": {
							"type": "object",
							"properties": {
								"answer": {
									"type": "string",
									"title": "Answer",
									"description": "The answer to the question. Ex: \"C. Evolution\". "
								},
								"points": {
									"type": "number",
									"format": "number",
									"title": "Points",
									"description": "How many points the correct answer is worth."
								}
							}
						}
					},
					"exemplar_answer": {
						"type": "string",
						"format": "html",
						"options": {
							"wysiwyg": true
						},
						"title": "Exemplar Answer"
					},
					"rubrique": {
						"type": "string",
						"format": "html",
						"options": {
							"wysiwyg": true
						},
						"title": "Rubrique"
					},
					"resource_activity_rubric_screenshots": {
						"title": "Screenshots",
						"type": "array",
						"items": {
							"type": "string",
							"title": "File",
							"description": "The name of the screenshot file. Format: RubricID_correct (for autograded) or RubricID_submitted (for non-autograded) Ex: \"CellularRespiration.LHA.InputsOutputs_Correct.jpg\". "
						}
					}
				}
			},
			"description": "IDs used to send sata to the sable website.",
			"options": {
				"collapsed": false
			}
		},
		"devEnv": {
			"title": "dev IDs",
			"$ref": "./serverEnvSchema.json",
			"options": {
				"collapsed": true
			}
		},
		"stageEnv": {
			"title": "Stage IDs",
			"$ref": "./serverEnvSchema.json",
			"options": {
				"collapsed": true
			}
		},
		"productionEnv": {
			"title": "Production IDs",
			"$ref": "./serverEnvSchema.json",
			"options": {
				"collapsed": true
			}
		}
	}
}

=== nicktayl0r/agb/project/config/rubrics.json
{
	"rubrics": [
		{
			"trackL": false,
			"trackH": false,
			"trackAP": false,
			"trackA": false,
			"trackE": true,
			"trackEX": true,
			"trackM": true,
			"trackMX": true,
			"key": "GroupBehavior.EExMMx.GroupSpeciesSurvival",
			"brief": "Select all the ways living in a group helps species survive.",
			"question": "Select all the ways living in a group helps species survive.",
			"resource_activity_rubric_skills": [
				"Core Concepts"
			],
			"resource_activity_rubric_type": "Multiple Choice",
			"autograde": true,
			"resource_activity_rubric_answers": [
				{
					"answer": "3 out of 3 correct options identified",
					"points": 3
				},
				{
					"answer": "2 out of 3 correct options identified",
					"points": 2
				},
				{
					"answer": "1 out of 3 correct options identified",
					"points": 1
				}
			],
			"exemplar_answer": "Protection against predators, help finding food and water, teaching young animals.<br />Living in a group helps species protect themselves, find food and water, and teach younger animals.",
			"rubrique": "1 point for each correct answer, only one try allowed.",
			"resource_activity_rubric_screenshots": [
				"GroupBehavior.EExMMx.GroupSpeciesSurvival_Correct.jpg"
			]
		},
		{
			"trackL": false,
			"trackH": false,
			"trackAP": false,
			"trackA": false,
			"trackE": true,
			"trackEX": true,
			"trackM": true,
			"trackMX": true,
			"key": "GroupBehavior.EExMMx.IdentifySenses",
			"brief": "Drag each sense to the correct spot.",
			"question": "Drag each sense to the correct spot.",
			"resource_activity_rubric_skills": [
				"Core Concepts"
			],
			"resource_activity_rubric_type": "Repeat Attempts",
			"autograde": true,
			"resource_activity_rubric_answers": [
				{
					"answer": "correct in 1 try",
					"points": 5
				},
				{
					"answer": "correct in 2 tries",
					"points": 3
				},
				{
					"answer": "correct in 3 tries",
					"points": 1
				}
			],
			"exemplar_answer": "See Screenshot for reference answer.",
			"rubrique": "Score depends on number of tries to get the correct answer.<ul> <li>5 points for one try</li><li>3 points for two tries</li><li>1 point for three tries, only three tries allowed</li></ul>",
			"resource_activity_rubric_screenshots": [
				"GroupBehavior.EExMMx.IdentifySenses_Correct.jpg"
			]
		},
		{
			"trackL": false,
			"trackH": false,
			"trackAP": false,
			"trackA": false,
			"trackE": false,
			"trackEX": true,
			"trackM": false,
			"trackMX": false,
			"key": "GroupBehavior.Ex.StructuresToFunctions",
			"brief": "Match the structures with their functions.",
			"question": "Match the structures with their functions.",
			"resource_activity_rubric_skills": [
				"Core Concepts"
			],
			"resource_activity_rubric_type": "Repeat Attempts",
			"autograde": true,
			"resource_activity_rubric_answers": [
				{
					"answer": "correct in 1 try",
					"points": 2
				},
				{
					"answer": "correct in 2 tries",
					"points": 1
				}
			],
			"exemplar_answer": "See Screenshot for reference answer.",
			"rubrique": "Score depends on number of tries to get the correct answer.<ul> <li>2 points for one try</li><li>1 point for two tries, only two tries allowed</li></ul>",
			"resource_activity_rubric_screenshots": [
				"GroupBehavior.Ex.StructuresToFunctions_Correct.jpg"
			]
		},
		{
			"trackL": false,
			"trackH": false,
			"trackAP": false,
			"trackA": false,
			"trackE": false,
			"trackEX": true,
			"trackM": false,
			"trackMX": true,
			"key": "GroupBehavior.ExMx.DeforestedGroupSize",
			"brief": "Do you think animal groups living in a deforested environment will be smaller or larger?",
			"question": "Do you think animal groups living in a deforested environment will be smaller or larger?",
			"resource_activity_rubric_skills": [
				"Core Concepts",
				"Predictions"
			],
			"resource_activity_rubric_type": "Multiple Choice",
			"autograde": true,
			"resource_activity_rubric_answers": [
				{
					"answer": "Smaller",
					"points": 1
				}
			],
			"exemplar_answer": "Smaller<br /><br />Animal groups living in a deforested environment will be smaller. <br />Because there are less resources after deforestation, groups will have to get smaller to survive.<br />They will have to move to find more resources.<br />",
			"rubrique": "1 point for the correct answer, only one try allowed.",
			"resource_activity_rubric_screenshots": [
				"GroupBehavior.ExMx.DeforestedGroupSize_Correct.jpg"
			]
		},
		{
			"trackL": false,
			"trackH": false,
			"trackAP": false,
			"trackA": false,
			"trackE": false,
			"trackEX": true,
			"trackM": false,
			"trackMX": true,
			"key": "GroupBehavior.ExMx.DeforestedGroupSizeExplanation",
			"brief": "Do you think animal groups living in a deforested environment will be smaller or larger? Explain your answer. \n",
			"question": "Explain your answer. ",
			"resource_activity_rubric_skills": [
				"Hypothesis & Reasoning"
			],
			"resource_activity_rubric_type": "Short Answer",
			"autograde": false,
			"resource_activity_rubric_answers": [
				{
					"answer": "Teacher Graded",
					"points": 2
				}
			],
			"exemplar_answer": "Animal groups living in a deforested environment will be smaller. This is because there are less resources after deforestation. Groups will have to get smaller to survive. They will have to move to find more resources.",
			"rubrique": "<li>1 point for clear and concise writing</li><li>1 point for explaining that less resources in an environment makes groups smaller</li>",
			"resource_activity_rubric_screenshots": [
				"GroupBehavior.ExMx.DeforestedGroupSizeExplanation_Submitted.jpg"
			]
		},
		{
			"trackL": false,
			"trackH": false,
			"trackAP": false,
			"trackA": false,
			"trackE": true,
			"trackEX": true,
			"trackM": true,
			"trackMX": true,
			"key": "GroupBehavior.EExMMx.OrderElephantEvents",
			"brief": "Click the events to put them in order from 1 to 4.",
			"question": "Click the events to put them in order from 1 to 4.",
			"resource_activity_rubric_skills": [
				"Core Concepts"
			],
			"resource_activity_rubric_type": "Repeat Attempts",
			"autograde": true,
			"resource_activity_rubric_answers": [
				{
					"answer": "correct in 1 try",
					"points": 3
				},
				{
					"answer": "correct in 2 tries",
					"points": 2
				},
				{
					"answer": "correct in 3 tries",
					"points": 1
				}
			],
			"exemplar_answer": "See Screenshot for reference answer.",
			"rubrique": "Score depends on number of tries to get the correct answer.<ul> <li>3 points for one try</li><li>2 point for two tries</li><li>1 points for three tries, only three tries allowed</li></ul>",
			"resource_activity_rubric_screenshots": [
				"GroupBehavior.EExMMx.OrderElephantEvents_Correct.jpg"
			]
		},
		{
			"trackL": false,
			"trackH": false,
			"trackAP": false,
			"trackA": false,
			"trackE": true,
			"trackEX": true,
			"trackM": true,
			"trackMX": true,
			"key": "GroupBehavior.EExMMx.ThingsElephantsLearn",
			"brief": "Select all the things below that elephants learn to stay away from bees.",
			"question": "Select all the things below that elephants learn to stay away from bees.",
			"resource_activity_rubric_skills": [
				"Core Concepts"
			],
			"resource_activity_rubric_type": "Multiple Choice",
			"autograde": true,
			"resource_activity_rubric_answers": [
				{
					"answer": "4 out of 4 correct options identified",
					"points": 2
				},
				{
					"answer": "3 out of 4 correct options identified",
					"points": 1
				}
			],
			"exemplar_answer": "<p>Seeing other elephants run away, the pain of a bee sting, the buzzing sound of bees, the look of beehives.</p><p>All of these are things that elephants have learned to run away from bees. <br><b></b><br></p>",
			"rubrique": "<p></p><ul><li>2 points for four out of four correct</li><li>1 point for three out of four correct, only two tries allowed</li></ul><p></p>",
			"resource_activity_rubric_screenshots": [
				"GroupBehavior.EExMMx.ThingsElephantsLearn_Correct.jpg"
			]
		},
		{
			"trackL": false,
			"trackH": false,
			"trackAP": false,
			"trackA": false,
			"trackE": true,
			"trackEX": false,
			"trackM": false,
			"trackMX": false,
			"key": "GroupBehavior.E.FarmTotalSquares",
			"brief": "Each square is 10 meters long and 10 meters wide. \nThis means that the field is 10 squares long and 5 squares wide.\nWhat is the total number of squares in the field?",
			"question": "What is the total number of squares in the field?",
			"resource_activity_rubric_skills": [
				"Data Analysis"
			],
			"resource_activity_rubric_type": "Multiple Choice",
			"autograde": true,
			"resource_activity_rubric_answers": [
				{
					"answer": "50 squares",
					"points": 1
				}
			],
			"exemplar_answer": "<p>50 squares</p><p><br>The total number of squares is 50, because it is 10 squares long and 5 squares wide (10 x 5 = 50).<br><br></p>",
			"rubrique": "1 point for the correct answer, only one try allowed.",
			"resource_activity_rubric_screenshots": [
				"GroupBehavior.E.FarmTotalSquares_Correct.jpg"
			]
		},
		{
			"trackL": false,
			"trackH": false,
			"trackAP": false,
			"trackA": false,
			"trackE": false,
			"trackEX": false,
			"trackM": true,
			"trackMX": false,
			"key": "GroupBehavior.M.FarmTotalArea",
			"brief": "The field is 100 meters long and 50 meters wide. \nWhat is the area of the field? (Area = length x width)",
			"question": "What is the area of the field? (Area = length x width)",
			"resource_activity_rubric_skills": [
				"Data Analysis"
			],
			"resource_activity_rubric_type": "Multiple Choice",
			"autograde": true,
			"resource_activity_rubric_answers": [
				{
					"answer": "5,000 square meters",
					"points": 1
				}
			],
			"exemplar_answer": "<p>5,000 square meters.<br><br>The field is a rectangle and the area of the rectangle is the length multiplied by the width (100 x 50 = 5,000).<br></p>",
			"rubrique": "1 point for the correct answer, only one try allowed.",
